FROM nginx:stable-alpine

MAINTAINER authors="cipchk <cipchk@qq.com>"

COPY /usr/src/_nginx/default.conf /etc/nginx/conf.d/

RUN rm -rf /usr/share/nginx/html/*

COPY /usr/src/dist/browser /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
