FROM nginx:stable-alpine

MAINTAINER authors="cipchk <cipchk@qq.com>"

WORKDIR /usr/src

RUN git clone --depth 1 --branch gh-pages https://github.com/ng-alain/delon.git dist \
    && sed -i 's/\/delon\//\//g' /usr/src/dist/index.html \
    && sed -i 's/\/delon\//\//g' /usr/src/dist/404.html

COPY _nginx _nginx
