FROM node:10 as build

LABEL authors="cipchk <cipchk@qq.com>"

WORKDIR /app

COPY . .

RUN npm i \
    && npm run site:build

FROM nginx:stable-alpine

COPY --from=build /app/_nginx/default.conf /etc/nginx/conf.d/
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/src/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
