FROM node:10

LABEL authors="cipchk <cipchk@qq.com>"

WORKDIR /app

COPY . .

RUN npm i \
    && ls \
    && npm run site:build

WORKDIR /dist
EXPOSE 80

COPY /app/_nginx/default.conf /etc/nginx/conf.d/
RUN rm -rf /usr/share/nginx/html/*
COPY /app/src/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
