FROM node:8

LABEL authors="cipchk <cipchk@qq.com>"

WORKDIR /usr/src/app

COPY package.json package.json

RUN yarn

COPY . .

RUN apt-get update && apt-get install -y dos2unix \
    && dos2unix site.sh \
    && bash site.sh -b
