engineStrict: false
autoInstallPeers: false
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - eslint-plugin-jsdoc@64.2.0
