engineStrict: false
autoInstallPeers: false
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - eslint-plugin-jsdoc@64.2.0
  - '@typescript-eslint/eslint-plugin@8.70.1'
  - '@typescript-eslint/parser@8.70.1'
  - '@typescript-eslint/project-service@8.70.1'
  - '@typescript-eslint/scope-manager@8.70.1'
  - '@typescript-eslint/tsconfig-utils@8.70.1'
  - '@typescript-eslint/type-utils@8.70.1'
  - '@typescript-eslint/types@8.70.1'
  - '@typescript-eslint/typescript-estree@8.70.1'
  - '@typescript-eslint/utils@8.70.1'
  - '@typescript-eslint/visitor-keys@8.70.1'
  - typescript-eslint@8.70.1
  - '@vitest/browser-playwright@5.0.2'
  - '@vitest/browser@5.0.2'
  - '@vitest/coverage-istanbul@5.0.2'
  - '@vitest/coverage-v8@5.0.2'
  - '@vitest/mocker@5.0.2'
  - '@vitest/pretty-format@5.0.2'
  - '@vitest/spy@5.0.2'
  - '@vitest/ui@5.0.2'
  - '@vitest/utils@5.0.2'
  - lint-staged@17.6.0
  - vitest@5.0.2
