engineStrict: false
autoInstallPeers: false
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - eslint-plugin-jsdoc@64.2.0
  - '@typescript-eslint/eslint-plugin@8.70.1'
  - '@typescript-eslint/parser@8.70.1'
  - '@typescript-eslint/project-service@8.70.1'
  - '@typescript-eslint/scope-manager@8.70.1'
  - '@typescript-eslint/tsconfig-utils@8.70.1'
  - '@typescript-eslint/type-utils@8.70.1'
  - '@typescript-eslint/types@8.70.1'
  - '@typescript-eslint/typescript-estree@8.70.1'
  - '@typescript-eslint/utils@8.70.1'
  - '@typescript-eslint/visitor-keys@8.70.1'
  - typescript-eslint@8.70.1
