#!/usr/bin/env bash

# Use for PATCH releases
# Publish all packages in `dist/packages-dist` to npm

(cd dist/packages-dist; for p in `ls .`; do curl -X PUT https://npm.taobao.org/sync/@delon/$p?sync_upstream=true; done)

curl -X PUT https://npm.taobao.org/sync/ng-alain?sync_upstream=true
