import { normalize } from '@angular-devkit/core';
import { Rule, SchematicsException, Tree, chain, SchematicContext } from '@angular-devkit/schematics';
import { ProjectDefinition } from '@schematics/angular/utility/workspace';
import { rmSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { parse } from 'jsonc-parser';
import { color } from 'listr2';
import { resolve, join } from 'path';
import { generateApi, GenerateApiParams } from 'swagger-typescript-api';

import { Schema } from './schema';
import { STAConfig } from './types';
import { modifyJSON } from '../utils/json';
import { getProject, isMulitProject } from '../utils/workspace';

let project: ProjectDefinition;
let projectName: string;

/**
 * `swagger-typescript-api` exports a stale `GenerateApiOutput` type that still describes the v12
 * shape (object-form `getTemplate`, sync `formatTSContent`), so derive the result type instead.
 */
type GenerateApiResult = Awaited<ReturnType<typeof generateApi>>;

// `eslint-disable` keeps the generated code away from every other rule, while the targeted
// `eslint-enable` lets the project's own `prettier/prettier` rule (via `eslint --fix`, which the
// scaffold runs through lint-staged) reformat the file to the project code style.
const filePrefix = `/* eslint-disable */
/* eslint-enable prettier/prettier */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

`;

function addPathInTsConfig(name: string): Rule {
  return (tree: Tree) => {
    const mulitProject = isMulitProject(tree);
    const commandPrefix = mulitProject ? `projects/${projectName}/` : '';
    const tsConfigPath = 'tsconfig.json';
    const basePath = ['compilerOptions', 'paths'];
    modifyJSON(tree, tsConfigPath, {
      path: [...basePath, `@${name}`],
      value: [`${commandPrefix}src/app/_${name}/index`]
    });
    modifyJSON(tree, tsConfigPath, {
      path: [...basePath, `@${name}/*`],
      value: [`${commandPrefix}src/app/_${name}/*`]
    });
    return tree;
  };
}

function cleanOutput(p: string): void {
  try {
    rmSync(p, { recursive: true });
    mkdirSync(p);
  } catch {}
}

function tagsMapping(res: GenerateApiResult, config: STAConfig): void {
  if (config.tagsMapping != null && Object.keys(config.tagsMapping).length <= 0) return;

  res.configuration.routes.combined?.forEach(v => {
    const newModuleName = config.tagsMapping?.[v.moduleName];
    if (newModuleName != null) {
      v.moduleName = newModuleName;
      v.routes.forEach(route => {
        route.raw.moduleName = newModuleName;
      });
    }
  });
}

async function fix(
  output: string,
  res: GenerateApiResult,
  tree: Tree,
  context: SchematicContext,
  config: STAConfig
): Promise<void> {
  tagsMapping(res, config);
  const indexList = [`models`, `_base.service`];
  const basePath = normalize(join(project.root, output.replace(process.cwd(), '')));
  try {
    // definitions
    const dataTpl = res.getTemplate('dataContracts', 'data-contracts.eta') ?? '';
    const dataContent = res.renderTemplate(dataTpl, { ...res.configuration });
    tree.create(`${basePath}/models.ts`, filePrefix + (await res.formatTSContent(dataContent)));

    // Base Service
    const baseServiceTpl = res.getTemplate('baseService', 'base.service.eta') ?? '';
    const baseServiceContent = res.renderTemplate(baseServiceTpl, { ...res.configuration });
    tree.create(`${basePath}/_base.service.ts`, filePrefix + (await res.formatTSContent(baseServiceContent)));

    // Tag Service
    const dtoTypeTpl = res.getTemplate('dto-type', 'dto-type.eta') ?? '';
    const serviceTpl = res.getTemplate('service', 'service.eta') ?? '';
    for (const route of res.configuration.routes.combined ?? []) {
      const routeIndex: string[] = [];
      // dto
      const dtoContent = await res.formatTSContent(res.renderTemplate(dtoTypeTpl, { ...res.configuration, route }));
      if (dtoContent.trim().length > 10) {
        tree.create(`${basePath}/${route.moduleName}/dtos.ts`, filePrefix + dtoContent);
        routeIndex.push(`dtos`);
      }

      // service
      const serviceContent = res.renderTemplate(serviceTpl, { ...res.configuration, route });
      tree.create(
        `${basePath}/${route.moduleName}/service.ts`,
        filePrefix + (await res.formatTSContent(serviceContent))
      );
      routeIndex.push(`service`);

      // index.ts
      tree.create(
        `${basePath}/${route.moduleName}/index.ts`,
        filePrefix + routeIndex.map(name => `export * from './${name}';`).join('\n')
      );
      indexList.push(`${route.moduleName}/index`);
    }
    // Index
    tree.create(`${basePath}/index.ts`, filePrefix + indexList.map(name => `export * from './${name}';`).join('\n'));
  } catch (ex) {
    throw new SchematicsException(`Parse error: ${ex}`);
  }
}

function genProxy(config: STAConfig): Rule {
  return async (tree: Tree, context: SchematicContext): Promise<void> => {
    context.logger.info(color.blue(`- Name: ${config.name}`));
    const output = (config.output = resolve(process.cwd(), config.output ?? `./src/app/_${config.name}`));
    const templates = resolve(__dirname, './templates');
    if (config.url) {
      context.logger.info(color.blue(`- Using url data: ${config.url}`));
      // swagger-typescript-api v13 removed `disableStrictSSL` and now fetches through the global
      // `fetch`, which honours `NODE_TLS_REJECT_UNAUTHORIZED`. Self-signed certificates used to be
      // accepted unconditionally, so keep that behaviour instead of breaking those setups.
      process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';
    } else if (config.filePath) {
      context.logger.info(color.blue(`- Using file data: ${config.filePath}`));
    }
    context.logger.info(color.blue(`- Output: ${output}`));

    context.logger.info(color.blue(`Start generating...`));
    const options = {
      fileName: `${config.name}.ts`,
      url: config.url,
      input: config.filePath,
      spec: config.spec,
      output,
      templates,
      toJS: false,
      modular: true,
      cleanOutput: true,
      enumStyle: 'union',
      generateClient: true,
      extractRequestParams: false,
      generateResponses: false,
      generateRouteTypes: true,
      silent: true,
      moduleNameFirstTag: true,
      defaultResponseType: 'any',
      typePrefix: config.modelTypePrefix,
      hooks: {
        onInit: (c: { httpClientType: string }) => {
          c.httpClientType = config.httpClientType ?? '';
          return c;
        },
        onPrepareConfig: c => {
          if (!config.responseDataField) return c;

          const getDeepDataType = (ref?: string): any => {
            if (!ref) return undefined;

            let typeData = c.utils.getComponentByRef(ref)?.typeData as any;
            while (typeData != null && Array.isArray(typeData.allOf) && typeData.allOf.length > 0) {
              const nextRef = typeData.allOf[0].$ref;
              if (!nextRef) break;
              typeData = c.utils.getComponentByRef(nextRef)?.typeData;
            }
            return typeData;
          };

          c.routes.combined?.forEach(moduleInfo => {
            moduleInfo.routes.forEach((routeInfo: any) => {
              if (!routeInfo.responseBodySchema) return;
              try {
                const content = routeInfo.responseBodySchema.content;
                if (!content) return;

                const responseBodyContentFirstType = Object.keys(content).pop();
                if (!responseBodyContentFirstType) return;

                // Not every response schema is a `$ref` (inline objects, binaries, primitives);
                // only `$ref` responses can be unwrapped through the components map.
                const ref = content[responseBodyContentFirstType]?.schema?.$ref;
                if (!ref) return;

                const resDataType = getDeepDataType(ref);
                if (!resDataType) return;
                const fieldProperty = resDataType.properties?.[config.responseDataField!];
                if (!fieldProperty) return;
                routeInfo.response.type = fieldProperty.$parsed.content ?? 'any';
              } catch (ex) {
                throw new SchematicsException(`Parse data field error: ${ex}`);
              }
            });
          });
          return c;
        },
        onFormatTypeName: formattedModelName => {
          if (!config.modelTypePrefix) return formattedModelName;

          if (formattedModelName.startsWith(config.modelTypePrefix + config.modelTypePrefix)) {
            return formattedModelName.substring(config.modelTypePrefix.length);
          }
          return formattedModelName;
        }
      },
      ...(config.generateApiOptions as any)
    } as GenerateApiParams;

    try {
      const res = await generateApi(options);
      cleanOutput(output);
      await fix(output, res, tree, context, config);
    } catch (ex) {
      throw new SchematicsException(`Generate error: ${ex}`);
    }
  };
}

function finished(): Rule {
  return (_: Tree, context: SchematicContext) => {
    context.logger.info(color.green(`✓  Finished, refer to: https://ng-alain.com/cli/sta`));
  };
}

function tryLoadConfig(context: SchematicContext, configPath?: string): STAConfig | null {
  if (!configPath || configPath.length <= 0) return null;

  try {
    const configFile = resolve(process.cwd(), configPath);
    context.logger.info(color.blue(`- Use config file: ${configFile}`));
    if (existsSync(configFile)) {
      return parse(readFileSync(configFile).toString('utf8'));
    }
  } catch (err) {
    throw new SchematicsException(`Invalid config file ${err}`);
  }
  return null;
}

export default function (options: Schema): Rule {
  return async (tree: Tree, context: SchematicContext) => {
    const res = await getProject(tree, options.project);
    project = res.project;
    projectName = res.name;
    const config: STAConfig = {
      name: 'sta',
      ...options,
      ...tryLoadConfig(context, options.config)
    };
    if (typeof config.generateApiOptions === 'string') {
      try {
        config.generateApiOptions = JSON.parse(config.generateApiOptions);
      } catch (ex) {
        throw new SchematicsException(`Parse generateApiParams error: '${config.generateApiOptions}' => ${ex}`);
      }
    }

    return chain([addPathInTsConfig(config.name!), genProxy(config), finished()]);
  };
}
