// Custom icon static resources

import {
  CopyOutline,
  DashboardOutline,
  DingdingOutline,
  EditOutline,
  EllipsisOutline,
  FormOutline,
  GithubOutline,
  HeartOutline,
  InboxOutline,
  LayoutOutline,
  MenuFoldOutline,
  MenuOutline,
  MenuUnfoldOutline,
  RocketOutline,
  SearchOutline,
  SkinOutline,
  StarFill,
  StarOutline,
  ToolOutline,
  VerticalLeftOutline,
  VerticalRightOutline,
} from '@ant-design/icons-angular/icons';

export const ICONS = [
  CopyOutline,
  DashboardOutline,
  DingdingOutline,
  EditOutline,
  EllipsisOutline,
  FormOutline,
  GithubOutline,
  HeartOutline,
  HeartOutline,
  InboxOutline,
  LayoutOutline,
  MenuFoldOutline,
  MenuOutline,
  MenuUnfoldOutline,
  RocketOutline,
  SearchOutline,
  SkinOutline,
  StarFill,
  StarOutline,
  ToolOutline,
  VerticalLeftOutline,
  VerticalRightOutline,
];
