// Custom icon static resources

import {
  CodeSandboxOutline,
  CopyOutline,
  CopyrightOutline,
  DashboardOutline,
  DingdingOutline,
  DownloadOutline,
  EditOutline,
  EllipsisOutline,
  FolderOpenOutline,
  FolderOutline,
  FormOutline,
  GithubOutline,
  HeartOutline,
  InboxOutline,
  LayoutOutline,
  MenuFoldOutline,
  MenuOutline,
  MenuUnfoldOutline,
  RocketOutline,
  SearchOutline,
  SkinOutline,
  SnippetsOutline,
  StarFill,
  StarOutline,
  ThunderboltFill,
  ToolOutline,
  UserOutline,
  VerticalLeftOutline,
  VerticalRightOutline,
} from '@ant-design/icons-angular/icons';

export const ICONS = [
  CodeSandboxOutline,
  CopyOutline,
  CopyrightOutline,
  DashboardOutline,
  DingdingOutline,
  DownloadOutline,
  EditOutline,
  EllipsisOutline,
  FolderOpenOutline,
  FolderOutline,
  FormOutline,
  GithubOutline,
  HeartOutline,
  InboxOutline,
  LayoutOutline,
  MenuFoldOutline,
  MenuOutline,
  MenuUnfoldOutline,
  RocketOutline,
  SearchOutline,
  SkinOutline,
  SnippetsOutline,
  StarFill,
  StarOutline,
  ThunderboltFill,
  ToolOutline,
  UserOutline,
  VerticalLeftOutline,
  VerticalRightOutline,
];
