name: build-doc-site-docker

# on: push
on:
  push:
    branches:
      - master

jobs:
  website:
    if: "startsWith(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          # registry: registry.gitlab.com
          # username: ${{ secrets.GITLAB_USERNAME }}
          # password: ${{ secrets.GITLAB_PASSWORD }}
          # Docker Hub
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.docs
          push: true
          tags:
            cipchk/ng-alain-docs:latest
            # registry.gitlab.com/ng-alain/images:docs
