name: build-doc-site-aliyun-docker

# on: push
on:
  push:
    branches:
      - master

jobs:
  website:
    if: "startsWith(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Docker
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.docs
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/alain/docs:latest
