# TODO: 非ssr模式
# (pre-build) npm run site:build
# (to-delon-builds) bash ./scripts/ci/build-artifacts-site.sh

# TODO: ssr模式
# (pre-build) npm run ssr:build
# (to-delon-builds) bash ./scripts/ci/build-artifacts-site.sh -ssr

name: ng-alain-com

on: push

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: pre-build
        run: |
          npm run site:build

      - name: to-delon-builds
        if: "startsWith(github.event.commits[0].message, 'release')"
        run: |
          bash ./scripts/ci/build-artifacts-site.sh
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
